/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    ComposePanel: typeof import('./src/components/ComposePanel.vue')['default']
    CopyableField: typeof import('./src/components/CopyableField.vue')['default']
    DayPanel: typeof import('./src/components/DayPanel.vue')['default']
    IconBlog: typeof import('./src/components/icons/IconBlog.vue')['default']
    IconInstagram: typeof import('./src/components/icons/IconInstagram.vue')['default']
    IconLinkedIn: typeof import('./src/components/icons/IconLinkedIn.vue')['default']
    IconX: typeof import('./src/components/icons/IconX.vue')['default']
    LucideCalendarDays: typeof import('~icons/lucide/calendar-days')['default']
    LucideCheckCircle2: typeof import('~icons/lucide/check-circle2')['default']
    LucideChevronsUpDown: typeof import('~icons/lucide/chevrons-up-down')['default']
    LucideEye: typeof import('~icons/lucide/eye')['default']
    LucideEyeOff: typeof import('~icons/lucide/eye-off')['default']
    LucideGripVertical: typeof import('~icons/lucide/grip-vertical')['default']
    LucideMinus: typeof import('~icons/lucide/minus')['default']
    LucidePlay: typeof import('~icons/lucide/play')['default']
    LucidePlus: typeof import('~icons/lucide/plus')['default']
    LucideTriangleAlert: typeof import('~icons/lucide/triangle-alert')['default']
    LucideUpload: typeof import('~icons/lucide/upload')['default']
    LucideX: typeof import('~icons/lucide/x')['default']
    PasswordField: typeof import('./src/components/PasswordField.vue')['default']
    PlatformBadge: typeof import('./src/components/PlatformBadge.vue')['default']
    PostPill: typeof import('./src/components/PostPill.vue')['default']
    PostPreview: typeof import('./src/components/PostPreview.vue')['default']
    ProjectPanel: typeof import('./src/components/ProjectPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
